---
name: PerlCritic

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with PerlCritic
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install PerlCritic
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install libperl-critic-perl
      - name: Run PerlCritic
        shell: bash
        run: perlcritic *kml*
