---
name: PerlCritic

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with PerlCritic
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install PerlCritic
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install libperl-critic-perl
      - name: Run PerlCritic
        shell: bash
        run: perlcritic *kml*
